// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Supabase: استخدم DIRECT_URL للأوامر التي تحتاج اتصال مباشر (migrate/db push)
    // واترك DATABASE_URL (pooler) للتشغيل اليومي إذا رغبت.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
